version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/magneticio/vamp2cli
    steps:
      - checkout
      - run: mkdir -p ./artifacts
      - run: go get
      - run: ./build.sh local
      - run: cp ./bin/* ./artifacts
      - run: cp ./bin/vamp2cli-darwin-amd64 ./artifacts/vamp2cli-darwin-x86_64
      - run: ./bin/vamp2cli-linux-386 version clean > ./artifacts/version.txt
      - persist_to_workspace:
            root: ./artifacts
            paths:
            - .
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat ./artifacts/version.txt)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
