version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.3
    steps:
      - checkout
      - run: mkdir -p ./artifacts
      - run: go get golang.org/x/tools/cmd/cover
      - run: go get github.com/mattn/goveralls@v0.0.3
      - run: ./test.sh
      - run: $GOPATH/bin/goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_TOKEN
  publish-github-release:
    docker:
      - image: cibuilds/github:0.12
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: "Update version file"
          command: |
            wget https://github.com/magneticio/semver-shell/releases/download/v0.2.0/semver_version.sh
            chmod +x semver_version.sh
            ./semver_version.sh -l go -f "./cmd/semver/version.go" -o none
      - run: ./build.sh local
      - run: mkdir -p ./artifacts
      - run: cp ./bin/* ./artifacts
      - run: cp ./bin/vamp-darwin-amd64 ./artifacts/vamp-darwin-x86_64
      - run: cp ./bin/vamp-linux-amd64 ./artifacts/vamp-linux-x86_64
      - run: git config user.email "${GITHUB_EMAIL}"
      - run: git config user.name "${CIRCLE_PROJECT_USERNAME}"
      - run: ./semver_version.sh -l text -f ./artifacts/version.txt
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat ./artifacts/version.txt)
            rm ./artifacts/version.txt
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^(v)\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              only:
                - master
